LANGUAGE = "es"

SCREEN_WIDTH = None
SCREEN_HEIGHT = None

CAMERA_DIGITAL_ZOOM_MIN = 1.0
CAMERA_DIGITAL_ZOOM_MAX = 2.5
CAMERA_DIGITAL_ZOOM_STEP = 0.1
CAMERA_DIGITAL_ZOOM = 1.0

SMOOTHING = 0.2
X_GAIN = 1.4
Y_GAIN = 3.4

CURSOR_DEADZONE_X = 0.02
CURSOR_DEADZONE_Y = 0.035
CURSOR_RESPONSE_POWER_X = 1.30
CURSOR_RESPONSE_POWER_Y = 1.55

USE_ADAPTIVE_SMOOTHING = True
SMOOTHING_MIN_ALPHA_X = 0.08
SMOOTHING_MAX_ALPHA_X = 0.35
SMOOTHING_PRECISION_DISTANCE_X = 8
SMOOTHING_FAST_DISTANCE_X = 160
SMOOTHING_MIN_ALPHA_Y = 0.04
SMOOTHING_MAX_ALPHA_Y = 0.22
SMOOTHING_PRECISION_DISTANCE_Y = 14
SMOOTHING_FAST_DISTANCE_Y = 220
SMOOTHING_MAX_Y_STEP = 18

USE_PRECISION_ASSIST = True
PRECISION_ENTER_SPEED = 6
PRECISION_EXIT_SPEED = 45
PRECISION_STABILITY_FRAMES = 8
PRECISION_ALPHA = 0.18
PRECISION_MICRO_DEADZONE = 3

USE_DYNAMIC_EDGE_PRECISION = True
PRECISION_EDGE_EXTRA_ENTER_SPEED = 8
PRECISION_EDGE_EXTRA_EXIT_SPEED = 35
PRECISION_EDGE_EXTRA_MICRO_DEADZONE = 7
PRECISION_EDGE_ALPHA = 0.10
PRECISION_EDGE_FACTOR_POWER = 1.35

DWELL_TIME = 1.2
DWELL_MOVE_THRESHOLD = 35
DWELL_COOLDOWN_TIME = 0.8
DWELL_EXIT_THRESHOLD = 55
DWELL_REQUIRE_EXIT_AFTER_CLICK = True

JAW_OPEN_THRESHOLD = 0.45
SMILE_THRESHOLD = 0.35
EYEBROWS_RAISED_THRESHOLD = 0.45
EYE_CLOSED_THRESHOLD = 0.38
EYE_WINK_OTHER_EYE_MAX = 0.24

TOGGLE_PAUSE_GESTURE = "GESTURE_MOUTH_OPEN"
COMMAND_MENU_GESTURE = "GESTURE_WINK_LEFT"
PAUSE_GESTURE_HOLD_TIME = 1.2
COMMAND_GESTURE_HOLD_TIME = 0.25
PAUSE_GESTURE_COOLDOWN_TIME = 1.2
COMMAND_GESTURE_COOLDOWN_TIME = 0.25

COMMAND_BAR_OPTION_WIDTH = 116
COMMAND_BAR_OPTION_HEIGHT = 72
COMMAND_BAR_GAP = 6

SCROLL_INTERVAL = 0.035
SCROLL_DEADZONE_Y = 0.018
SCROLL_DEADZONE_X = 0.030
SCROLL_GAIN_Y = 360
SCROLL_GAIN_X = 220
SCROLL_MIN_AMOUNT = 10
SCROLL_MAX_AMOUNT = 40

FACE_LOST_PAUSE_TIME = 1.0
MINIMIZE_CONSOLE_AFTER_CALIBRATION = True

KEYBOARD_WIDTH_RATIO = 0.92
KEYBOARD_MAX_WIDTH = 1550
KEYBOARD_BOTTOM_MARGIN_RATIO = 0.040
KEYBOARD_KEY_HEIGHT_RATIO = 0.068
KEYBOARD_GAP_RATIO = 0.006
KEYBOARD_PROTECTION_MARGIN = 22