from enum import Enum


class Event(str, Enum):
    CLICK_LEFT = "CLICK_LEFT"
    CLICK_RIGHT = "CLICK_RIGHT"
    DOUBLE_CLICK = "DOUBLE_CLICK"

    MOUSE_DOWN_LEFT = "MOUSE_DOWN_LEFT"
    MOUSE_UP_LEFT = "MOUSE_UP_LEFT"

    SCROLL_UP = "SCROLL_UP"
    SCROLL_DOWN = "SCROLL_DOWN"
    SCROLL_LEFT = "SCROLL_LEFT"
    SCROLL_RIGHT = "SCROLL_RIGHT"


    GESTURE_MOUTH_OPEN = "GESTURE_MOUTH_OPEN"
    GESTURE_SMILE = "GESTURE_SMILE"
    GESTURE_WINK_LEFT = "GESTURE_WINK_LEFT"
    GESTURE_WINK_RIGHT = "GESTURE_WINK_RIGHT"
    GESTURE_EYEBROWS_RAISED = "GESTURE_EYEBROWS_RAISED"


    TOGGLE_PAUSE = "TOGGLE_PAUSE"
    OPEN_COMMAND_MENU = "OPEN_COMMAND_MENU"


    COMMAND_RIGHT_CLICK = "COMMAND_RIGHT_CLICK"
    COMMAND_DOUBLE_CLICK = "COMMAND_DOUBLE_CLICK"
    COMMAND_SCROLL = "COMMAND_SCROLL"
    COMMAND_DRAG = "COMMAND_DRAG"
    COMMAND_KEYBOARD = "COMMAND_KEYBOARD"
    COMMAND_HELP = "COMMAND_HELP"
    COMMAND_EXIT = "COMMAND_EXIT"
    COMMAND_CANCEL = "COMMAND_CANCEL"

    @classmethod
    def from_value(cls, value):
        if isinstance(value, cls):
            return value

        try:
            return cls(value)
        except ValueError:
            return None
